name: Ruff

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  ruff:
    runs-on: codeberg-tiny-lazy

    container:
      image: docker.io/library/python:3.13-slim

    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4

      - name: Install Ruff
        run: pip install ruff

      - name: Ruff check
        run: ruff check .

      - name: Ruff format check
        run: ruff format --check .