name: Ruff

on:
  push:
  pull_request:

jobs:
  ruff:
    runs-on: docker

    container:
      image: python:3.13-slim

    steps:
      - name: Checkout repository
        uses: https://code.forgejo.org/actions/checkout@v4

      - name: Install Ruff
        run: pip install ruff

      - name: Ruff check
        run: ruff check .

      - name: Ruff format check
        run: ruff format --check .
